#!/usr/bin/env node
'use strict';

const net = require('net');

const name = process.argv[2];
if (!name) {
  process.stderr.write('usage: hostcmd <command>\n');
  process.exit(1);
}

const session = process.env.SANDBOX_SESSION;
if (!session) {
  process.stderr.write('hostcmd: SANDBOX_SESSION not set (not in a sandbox session?)\n');
  process.exit(1);
}

const port = parseInt(process.env.SANDBOX_HOSTCMD_PORT || '9847', 10);
const host = 'host.docker.internal';

const client = net.createConnection({ host, port }, () => {
  client.write(JSON.stringify({ type: 'execute', session, command: name }) + '\n');
});

let buf = '';
client.on('data', (chunk) => { buf += chunk; });

client.on('end', () => {
  try {
    const resp = JSON.parse(buf.trim());
    if (resp.output) process.stdout.write(resp.output);
    process.exit(resp.exit_code || 0);
  } catch (e) {
    process.stderr.write('hostcmd: bad response from host\n');
    process.exit(1);
  }
});

client.on('error', (err) => {
  process.stderr.write('hostcmd: cannot connect to host daemon: ' + err.message + '\n');
  process.exit(1);
});
